variables:
  - group: ADO_HCLAppScanPlugin
  
pool:
  vmImage: ubuntu-latest

jobs:
- job: ADO_Regression_ASoC_SAST_GenerateIRX_largeProjectScan_YAML
  timeoutInMinutes: 9999
  
  steps:
  - task: HCLAppScanOnCloud@2
    timeoutInMinutes: 1440
    displayName: 'Run HCL AppScan on Cloud/HCL AppScan 360° Security Test'
    inputs:
      AppSecTestService: '$(ASoC_CREDENTIALS)'
      applications: '$(ASoC_AppID)'
      scanname: 'ADO_Regression_ASoC_SAST_GenerateIRX_largeProjectScan_YAML'
      ScanSpeedOptions: simple
      type: staging
      loginMethod: None
      network: public
      optimization: fastest
      networkFile: public
      intervention: false
